GPU_ID: '0' 
model_restore: '' 

log_dir: exp/logs/stomach_logs
dir_video: '../content/Implicit-Internal-Video-Inpainting/inputs/videos/stomach_images_56' 
dir_mask: '../content/Implicit-Internal-Video-Inpainting/inputs/masks/mask'

# training
img_shapes: [488, 640]
batch_size: 5
lr: 0.0002

max_iters: 30000
max_epochs: 20000
print_iters: 50
summary_iters: 2500
model_iters: 10000


# Network
coarse_only: False 
use_refine: True 
padding: 'SAME'


# loss
stabilization_loss: False 
ambiguity_loss: False
l1_loss: True
l1_loss_alpha: 1.
stabilization_loss_alpha: 0.2 
ambiguity_loss_alpha: 0.1
